### ISSUE TITLE
How to get the MAC address?

### ISSUE THREAD

**Issue by Slion** [minhe7735/GearVR-Controller-WIndows#2]
I just ordered one of those controller to try it out.
How do I get the MAC address for it?
Thanks for sharing that project by the way, it looks awesome.

**Comment by minhe7735** [comment]
First try to connect it like how you would with any bluetooth device. Then open device manager -> bluetooth -> Gear VR Controller. Right click it and go to properties. Go to details tab and click Association Endpoint address.

**Comment by Slion** [comment]
Works great, thanks!
