### ISSUE TITLE
App Autoclose on minimise

### ISSUE THREAD

**Issue by safdar9633** [minhe7735/GearVR-Controller-WIndows#6]
The app is auto closing when minimized..

**Comment by minhe7735** [comment]
it should minimize to tray. Is it not there?

**Comment by safdar9633** [comment]
No it just closes. And even in the background process it just goes away after few seconds.

**Comment by safdar9633** [comment]
Strange I tried 2 Pcs all having the same issue of closing on minimize. And if you could please tell me how can we set it to autoconnect when app is started so I can add the app on windows starup and it connects automatically

**Comment by minhe7735** [comment]
okay, I may have an idea on what the issue might be. I'll try go get the update out sometimes next week.

**Comment by safdar9633** [comment]
Thank you.. This made my life easier.. I am using a windows laptop hooked up to my TV as a smart TV.. This is so good and acts eaxctly like a remote..

**Comment by minhe7735** [comment]
should be fixed in new release

**Comment by safdar9633** [comment]
Thanks a Ton Mate! Its working perfect now!!!!
